name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Java (for example, using Maven for building the project)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Step 3: Build the project using Maven (similar to 'mvn clean package')
      - name: Build Project
        run: mvn clean package

  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code again
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Run tests using Maven (similar to 'mvn test')
      - name: Run Tests
        run: mvn test

  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Deploy (You can replace this with your own deploy script or Docker command)
      - name: Deploy Project
        run: ./deploy.sh  # or any deployment command/script for your project
